[package]
name = "safemem"
version = "0.1.0"
authors = ["Austin Bonander <austin.bonander@gmail.com>"]

description = "Safe wrappers for memory-accessing functions, like `std::ptr::copy()`."


[dependencies]
